#!/bin/sh

# ===================================================================
#
# Script for running wiki2owl
#
# ===================================================================

MN_DIST_DIR=@@@DISTDIR@@@
MAIN_CLASS=edu.berkeley.icsi.metanet.wiki2owl.WikiParserCmd

CLASSPATH=$MN_DIST_DIR/lib/wiki2owl.jar:$MN_DIST_DIR/lib/commons-cli-1.2.jar:$MN_DIST_DIR/lib/commons-lang3-3.1.jar:$MN_DIST_DIR/lib/wikiapi.jar:$MN_DIST_DIR/lib/org.semanticweb.owl.owlapi.jar
export CLASSPATH

SSL_OPTS="-Djavax.net.ssl.trustStore=$MN_DIST_DIR/etc/wiki/truststore.db -Djavax.net.ssl.trustStorePassword=changeit -Djavax.net.ssl.trustStoreType=JKS"

java $JAVA_OPTS $SSL_OPTS $MAIN_CLASS $@
