package edu.berkeley.icsi.metanet.repository;

import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLDataProperty;
import org.semanticweb.owlapi.model.OWLObjectProperty;

/**
 * Vocabulary class to provide access to the Manchester OWL API representatives for 
 * various entities in the ontology used to generate this code.<p> 
 * 
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: ${javaClass}
 *
 * @version generated on Tue Mar 05 15:42:48 PST 2013 by jhong
 */

public class Vocabulary {

	private static final OWLDataFactory factory = OWLManager.createOWLOntologyManager().getOWLDataFactory();

    /* ***************************************************
     * Class https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#AutoMetaphor
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class AUTOMETAPHOR.<p>
     * 
     */
    public static final OWLClass CLASS_AUTOMETAPHOR = factory.getOWLClass(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#AutoMetaphor"));

    /* ***************************************************
     * Class https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#AutoSchema
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class AUTOSCHEMA.<p>
     * 
     */
    public static final OWLClass CLASS_AUTOSCHEMA = factory.getOWLClass(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#AutoSchema"));

    /* ***************************************************
     * Class https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#Binding
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BINDING.<p>
     * 
     */
    public static final OWLClass CLASS_BINDING = factory.getOWLClass(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#Binding"));

    /* ***************************************************
     * Class https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#Entailment
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ENTAILMENT.<p>
     * 
     */
    public static final OWLClass CLASS_ENTAILMENT = factory.getOWLClass(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#Entailment"));

    /* ***************************************************
     * Class https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#Example
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class EXAMPLE.<p>
     * 
     */
    public static final OWLClass CLASS_EXAMPLE = factory.getOWLClass(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#Example"));

    /* ***************************************************
     * Class https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#Inference
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class INFERENCE.<p>
     * 
     */
    public static final OWLClass CLASS_INFERENCE = factory.getOWLClass(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#Inference"));

    /* ***************************************************
     * Class https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#LexicalUnit
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LEXICALUNIT.<p>
     * 
     */
    public static final OWLClass CLASS_LEXICALUNIT = factory.getOWLClass(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#LexicalUnit"));

    /* ***************************************************
     * Class https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#LinguisticMetaphor
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LINGUISTICMETAPHOR.<p>
     * 
     */
    public static final OWLClass CLASS_LINGUISTICMETAPHOR = factory.getOWLClass(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#LinguisticMetaphor"));

    /* ***************************************************
     * Class https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#Mapping
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MAPPING.<p>
     * 
     */
    public static final OWLClass CLASS_MAPPING = factory.getOWLClass(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#Mapping"));

    /* ***************************************************
     * Class https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#Metaphor
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class METAPHOR.<p>
     * 
     */
    public static final OWLClass CLASS_METAPHOR = factory.getOWLClass(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#Metaphor"));

    /* ***************************************************
     * Class https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#MetaphorFamily
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class METAPHORFAMILY.<p>
     * 
     */
    public static final OWLClass CLASS_METAPHORFAMILY = factory.getOWLClass(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#MetaphorFamily"));

    /* ***************************************************
     * Class https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#Role
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ROLE.<p>
     * 
     */
    public static final OWLClass CLASS_ROLE = factory.getOWLClass(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#Role"));

    /* ***************************************************
     * Class https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#Schema
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SCHEMA.<p>
     * 
     */
    public static final OWLClass CLASS_SCHEMA = factory.getOWLClass(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#Schema"));

    /* ***************************************************
     * Class https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#SchemaFamily
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SCHEMAFAMILY.<p>
     * 
     */
    public static final OWLClass CLASS_SCHEMAFAMILY = factory.getOWLClass(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#SchemaFamily"));

    /* ***************************************************
     * Class https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#VettedMetaphor
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class VETTEDMETAPHOR.<p>
     * 
     */
    public static final OWLClass CLASS_VETTEDMETAPHOR = factory.getOWLClass(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#VettedMetaphor"));

    /* ***************************************************
     * Class https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#VettedSchema
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class VETTEDSCHEMA.<p>
     * 
     */
    public static final OWLClass CLASS_VETTEDSCHEMA = factory.getOWLClass(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#VettedSchema"));

    /* ***************************************************
     * Object Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#dependsOnMappings
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property DEPENDSONMAPPINGS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_DEPENDSONMAPPINGS = factory.getOWLObjectProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#dependsOnMappings"));

    /* ***************************************************
     * Object Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#entailsMetaphor
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ENTAILSMETAPHOR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ENTAILSMETAPHOR = factory.getOWLObjectProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#entailsMetaphor"));

    /* ***************************************************
     * Object Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasBindings
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASBINDINGS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASBINDINGS = factory.getOWLObjectProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasBindings"));

    /* ***************************************************
     * Object Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasBoundRole1
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASBOUNDROLE1.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASBOUNDROLE1 = factory.getOWLObjectProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasBoundRole1"));

    /* ***************************************************
     * Object Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasBoundRole2
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASBOUNDROLE2.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASBOUNDROLE2 = factory.getOWLObjectProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasBoundRole2"));

    /* ***************************************************
     * Object Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasBoundRoles
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASBOUNDROLES.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASBOUNDROLES = factory.getOWLObjectProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasBoundRoles"));

    /* ***************************************************
     * Object Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasEntailment
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASENTAILMENT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASENTAILMENT = factory.getOWLObjectProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasEntailment"));

    /* ***************************************************
     * Object Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasExample
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASEXAMPLE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASEXAMPLE = factory.getOWLObjectProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasExample"));

    /* ***************************************************
     * Object Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasInference
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASINFERENCE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASINFERENCE = factory.getOWLObjectProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasInference"));

    /* ***************************************************
     * Object Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasLexicalUnit
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASLEXICALUNIT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASLEXICALUNIT = factory.getOWLObjectProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasLexicalUnit"));

    /* ***************************************************
     * Object Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasMappings
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASMAPPINGS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASMAPPINGS = factory.getOWLObjectProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasMappings"));

    /* ***************************************************
     * Object Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasMetaphors
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASMETAPHORS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASMETAPHORS = factory.getOWLObjectProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasMetaphors"));

    /* ***************************************************
     * Object Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasRoles
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASROLES.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASROLES = factory.getOWLObjectProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasRoles"));

    /* ***************************************************
     * Object Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasSchemas
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASSCHEMAS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASSCHEMAS = factory.getOWLObjectProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasSchemas"));

    /* ***************************************************
     * Object Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasSourceInference
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASSOURCEINFERENCE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASSOURCEINFERENCE = factory.getOWLObjectProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasSourceInference"));

    /* ***************************************************
     * Object Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasSourceRole
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASSOURCEROLE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASSOURCEROLE = factory.getOWLObjectProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasSourceRole"));

    /* ***************************************************
     * Object Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasSourceSchema
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASSOURCESCHEMA.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASSOURCESCHEMA = factory.getOWLObjectProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasSourceSchema"));

    /* ***************************************************
     * Object Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasTargetInference
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASTARGETINFERENCE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASTARGETINFERENCE = factory.getOWLObjectProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasTargetInference"));

    /* ***************************************************
     * Object Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasTargetRole
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASTARGETROLE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASTARGETROLE = factory.getOWLObjectProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasTargetRole"));

    /* ***************************************************
     * Object Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasTargetSchema
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASTARGETSCHEMA.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASTARGETSCHEMA = factory.getOWLObjectProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasTargetSchema"));

    /* ***************************************************
     * Object Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasTransitiveSubpart1Metaphor
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASTRANSITIVESUBPART1METAPHOR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASTRANSITIVESUBPART1METAPHOR = factory.getOWLObjectProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasTransitiveSubpart1Metaphor"));

    /* ***************************************************
     * Object Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasTransitiveSubpart2Metaphor
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASTRANSITIVESUBPART2METAPHOR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASTRANSITIVESUBPART2METAPHOR = factory.getOWLObjectProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasTransitiveSubpart2Metaphor"));

    /* ***************************************************
     * Object Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isBindingInSchema
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISBINDINGINSCHEMA.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISBINDINGINSCHEMA = factory.getOWLObjectProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isBindingInSchema"));

    /* ***************************************************
     * Object Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isDefinedRelativeToSchema
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISDEFINEDRELATIVETOSCHEMA.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISDEFINEDRELATIVETOSCHEMA = factory.getOWLObjectProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isDefinedRelativeToSchema"));

    /* ***************************************************
     * Object Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isEntailedByMetaphor
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISENTAILEDBYMETAPHOR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISENTAILEDBYMETAPHOR = factory.getOWLObjectProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isEntailedByMetaphor"));

    /* ***************************************************
     * Object Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isEntailmentOfMetaphor
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISENTAILMENTOFMETAPHOR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISENTAILMENTOFMETAPHOR = factory.getOWLObjectProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isEntailmentOfMetaphor"));

    /* ***************************************************
     * Object Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isExampleOfMetaphor
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISEXAMPLEOFMETAPHOR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISEXAMPLEOFMETAPHOR = factory.getOWLObjectProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isExampleOfMetaphor"));

    /* ***************************************************
     * Object Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isFromSeedMetaphor
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISFROMSEEDMETAPHOR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISFROMSEEDMETAPHOR = factory.getOWLObjectProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isFromSeedMetaphor"));

    /* ***************************************************
     * Object Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isInMetaphorFamily
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISINMETAPHORFAMILY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISINMETAPHORFAMILY = factory.getOWLObjectProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isInMetaphorFamily"));

    /* ***************************************************
     * Object Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isInSchemaFamily
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISINSCHEMAFAMILY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISINSCHEMAFAMILY = factory.getOWLObjectProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isInSchemaFamily"));

    /* ***************************************************
     * Object Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isInferenceOfSchema
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISINFERENCEOFSCHEMA.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISINFERENCEOFSCHEMA = factory.getOWLObjectProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isInferenceOfSchema"));

    /* ***************************************************
     * Object Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isInstanceOfMetaphor
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISINSTANCEOFMETAPHOR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISINSTANCEOFMETAPHOR = factory.getOWLObjectProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isInstanceOfMetaphor"));

    /* ***************************************************
     * Object Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isMappingUsedByMetaphors
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISMAPPINGUSEDBYMETAPHORS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISMAPPINGUSEDBYMETAPHORS = factory.getOWLObjectProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isMappingUsedByMetaphors"));

    /* ***************************************************
     * Object Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isMetaphorSubfamilyOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISMETAPHORSUBFAMILYOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISMETAPHORSUBFAMILYOF = factory.getOWLObjectProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isMetaphorSubfamilyOf"));

    /* ***************************************************
     * Object Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isMetaphorSuperfamilyOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISMETAPHORSUPERFAMILYOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISMETAPHORSUPERFAMILYOF = factory.getOWLObjectProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isMetaphorSuperfamilyOf"));

    /* ***************************************************
     * Object Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isRelatedToMetaphor
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISRELATEDTOMETAPHOR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISRELATEDTOMETAPHOR = factory.getOWLObjectProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isRelatedToMetaphor"));

    /* ***************************************************
     * Object Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isRelatedToMetaphorBySource
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISRELATEDTOMETAPHORBYSOURCE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISRELATEDTOMETAPHORBYSOURCE = factory.getOWLObjectProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isRelatedToMetaphorBySource"));

    /* ***************************************************
     * Object Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isRelatedToMetaphorByTarget
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISRELATEDTOMETAPHORBYTARGET.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISRELATEDTOMETAPHORBYTARGET = factory.getOWLObjectProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isRelatedToMetaphorByTarget"));

    /* ***************************************************
     * Object Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isRelatedToSchema
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISRELATEDTOSCHEMA.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISRELATEDTOSCHEMA = factory.getOWLObjectProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isRelatedToSchema"));

    /* ***************************************************
     * Object Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isRoleOfSchema
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISROLEOFSCHEMA.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISROLEOFSCHEMA = factory.getOWLObjectProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isRoleOfSchema"));

    /* ***************************************************
     * Object Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isSchemaSubfamilyOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISSCHEMASUBFAMILYOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISSCHEMASUBFAMILYOF = factory.getOWLObjectProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isSchemaSubfamilyOf"));

    /* ***************************************************
     * Object Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isSchemaSuperfamilyOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISSCHEMASUPERFAMILYOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISSCHEMASUPERFAMILYOF = factory.getOWLObjectProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isSchemaSuperfamilyOf"));

    /* ***************************************************
     * Object Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isSourceDomainOfMetaphors
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISSOURCEDOMAINOFMETAPHORS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISSOURCEDOMAINOFMETAPHORS = factory.getOWLObjectProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isSourceDomainOfMetaphors"));

    /* ***************************************************
     * Object Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isSourceInferenceOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISSOURCEINFERENCEOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISSOURCEINFERENCEOF = factory.getOWLObjectProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isSourceInferenceOf"));

    /* ***************************************************
     * Object Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isSourceSubcaseOfMetaphor
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISSOURCESUBCASEOFMETAPHOR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISSOURCESUBCASEOFMETAPHOR = factory.getOWLObjectProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isSourceSubcaseOfMetaphor"));

    /* ***************************************************
     * Object Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isSourceSupercaseOfMetaphor
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISSOURCESUPERCASEOFMETAPHOR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISSOURCESUPERCASEOFMETAPHOR = factory.getOWLObjectProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isSourceSupercaseOfMetaphor"));

    /* ***************************************************
     * Object Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isSubcaseOfMetaphor
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISSUBCASEOFMETAPHOR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISSUBCASEOFMETAPHOR = factory.getOWLObjectProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isSubcaseOfMetaphor"));

    /* ***************************************************
     * Object Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isSubcaseOfSchema
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISSUBCASEOFSCHEMA.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISSUBCASEOFSCHEMA = factory.getOWLObjectProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isSubcaseOfSchema"));

    /* ***************************************************
     * Object Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isSubprocessOfSchema
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISSUBPROCESSOFSCHEMA.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISSUBPROCESSOFSCHEMA = factory.getOWLObjectProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isSubprocessOfSchema"));

    /* ***************************************************
     * Object Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isSupercaseOfMetaphor
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISSUPERCASEOFMETAPHOR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISSUPERCASEOFMETAPHOR = factory.getOWLObjectProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isSupercaseOfMetaphor"));

    /* ***************************************************
     * Object Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isSupercaseOfSchema
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISSUPERCASEOFSCHEMA.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISSUPERCASEOFSCHEMA = factory.getOWLObjectProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isSupercaseOfSchema"));

    /* ***************************************************
     * Object Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isSuperprocessOfSchema
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISSUPERPROCESSOFSCHEMA.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISSUPERPROCESSOFSCHEMA = factory.getOWLObjectProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isSuperprocessOfSchema"));

    /* ***************************************************
     * Object Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isTargetDomainOfMetaphors
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISTARGETDOMAINOFMETAPHORS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISTARGETDOMAINOFMETAPHORS = factory.getOWLObjectProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isTargetDomainOfMetaphors"));

    /* ***************************************************
     * Object Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isTargetInferenceOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISTARGETINFERENCEOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISTARGETINFERENCEOF = factory.getOWLObjectProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isTargetInferenceOf"));

    /* ***************************************************
     * Object Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isTargetSubcaseOfMetaphor
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISTARGETSUBCASEOFMETAPHOR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISTARGETSUBCASEOFMETAPHOR = factory.getOWLObjectProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isTargetSubcaseOfMetaphor"));

    /* ***************************************************
     * Object Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isTargetSupercaseOfMetaphor
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISTARGETSUPERCASEOFMETAPHOR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISTARGETSUPERCASEOFMETAPHOR = factory.getOWLObjectProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isTargetSupercaseOfMetaphor"));

    /* ***************************************************
     * Object Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isTransitiveSubpart1OfMetaphor
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISTRANSITIVESUBPART1OFMETAPHOR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISTRANSITIVESUBPART1OFMETAPHOR = factory.getOWLObjectProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isTransitiveSubpart1OfMetaphor"));

    /* ***************************************************
     * Object Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isTransitiveSubpart2OfMetaphor
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISTRANSITIVESUBPART2OFMETAPHOR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISTRANSITIVESUBPART2OFMETAPHOR = factory.getOWLObjectProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isTransitiveSubpart2OfMetaphor"));

    /* ***************************************************
     * Object Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isUsedByMetaphor
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISUSEDBYMETAPHOR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISUSEDBYMETAPHOR = factory.getOWLObjectProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isUsedByMetaphor"));

    /* ***************************************************
     * Object Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isUsedBySchema
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISUSEDBYSCHEMA.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISUSEDBYSCHEMA = factory.getOWLObjectProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isUsedBySchema"));

    /* ***************************************************
     * Object Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#makesUseOfMetaphor
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property MAKESUSEOFMETAPHOR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_MAKESUSEOFMETAPHOR = factory.getOWLObjectProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#makesUseOfMetaphor"));

    /* ***************************************************
     * Object Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#makesUseOfSchema
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property MAKESUSEOFSCHEMA.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_MAKESUSEOFSCHEMA = factory.getOWLObjectProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#makesUseOfSchema"));

    /* ***************************************************
     * Object Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#participatesInBinding
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property PARTICIPATESINBINDING.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_PARTICIPATESINBINDING = factory.getOWLObjectProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#participatesInBinding"));

    /* ***************************************************
     * Object Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#supportsEntailments
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property SUPPORTSENTAILMENTS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_SUPPORTSENTAILMENTS = factory.getOWLObjectProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#supportsEntailments"));

    /* ***************************************************
     * Data Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#correspondsToFrameElement
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property CORRESPONDSTOFRAMEELEMENT.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_CORRESPONDSTOFRAMEELEMENT = factory.getOWLDataProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#correspondsToFrameElement"));

    /* ***************************************************
     * Data Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#correspondsToFrameNet
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property CORRESPONDSTOFRAMENET.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_CORRESPONDSTOFRAMENET = factory.getOWLDataProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#correspondsToFrameNet"));

    /* ***************************************************
     * Data Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasAlias
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASALIAS.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASALIAS = factory.getOWLDataProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasAlias"));

    /* ***************************************************
     * Data Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasAnnotation
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASANNOTATION.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASANNOTATION = factory.getOWLDataProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasAnnotation"));

    /* ***************************************************
     * Data Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasCulturalContent
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASCULTURALCONTENT.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASCULTURALCONTENT = factory.getOWLDataProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasCulturalContent"));

    /* ***************************************************
     * Data Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasDefinition
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASDEFINITION.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASDEFINITION = factory.getOWLDataProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasDefinition"));

    /* ***************************************************
     * Data Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasExperientialBasis
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASEXPERIENTIALBASIS.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASEXPERIENTIALBASIS = factory.getOWLDataProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasExperientialBasis"));

    /* ***************************************************
     * Data Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasInferenceType
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASINFERENCETYPE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASINFERENCETYPE = factory.getOWLDataProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasInferenceType"));

    /* ***************************************************
     * Data Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasInferentialContent
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASINFERENTIALCONTENT.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASINFERENTIALCONTENT = factory.getOWLDataProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasInferentialContent"));

    /* ***************************************************
     * Data Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasLemma
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASLEMMA.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASLEMMA = factory.getOWLDataProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasLemma"));

    /* ***************************************************
     * Data Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasLinguisticMetaphorType
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASLINGUISTICMETAPHORTYPE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASLINGUISTICMETAPHORTYPE = factory.getOWLDataProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasLinguisticMetaphorType"));

    /* ***************************************************
     * Data Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasLinguisticSource
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASLINGUISTICSOURCE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASLINGUISTICSOURCE = factory.getOWLDataProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasLinguisticSource"));

    /* ***************************************************
     * Data Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasLinguisticTarget
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASLINGUISTICTARGET.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASLINGUISTICTARGET = factory.getOWLDataProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasLinguisticTarget"));

    /* ***************************************************
     * Data Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasMetaphorLevel
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASMETAPHORLEVEL.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASMETAPHORLEVEL = factory.getOWLDataProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasMetaphorLevel"));

    /* ***************************************************
     * Data Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasMetaphorType
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASMETAPHORTYPE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASMETAPHORTYPE = factory.getOWLDataProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasMetaphorType"));

    /* ***************************************************
     * Data Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasName
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASNAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASNAME = factory.getOWLDataProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasName"));

    /* ***************************************************
     * Data Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasNameGloss
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASNAMEGLOSS.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASNAMEGLOSS = factory.getOWLDataProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasNameGloss"));

    /* ***************************************************
     * Data Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasRoleType
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASROLETYPE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASROLETYPE = factory.getOWLDataProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasRoleType"));

    /* ***************************************************
     * Data Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasSchemaType
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASSCHEMATYPE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASSCHEMATYPE = factory.getOWLDataProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasSchemaType"));

    /* ***************************************************
     * Data Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasSentence
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASSENTENCE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASSENTENCE = factory.getOWLDataProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasSentence"));

    /* ***************************************************
     * Data Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasSentenceGloss
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASSENTENCEGLOSS.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASSENTENCEGLOSS = factory.getOWLDataProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasSentenceGloss"));

    /* ***************************************************
     * Data Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasSentenceTranslation
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASSENTENCETRANSLATION.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASSENTENCETRANSLATION = factory.getOWLDataProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasSentenceTranslation"));

    /* ***************************************************
     * Data Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasVerificationStatus
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASVERIFICATIONSTATUS.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASVERIFICATIONSTATUS = factory.getOWLDataProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#hasVerificationStatus"));

    /* ***************************************************
     * Data Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isApplicableToLanguage
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property ISAPPLICABLETOLANGUAGE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_ISAPPLICABLETOLANGUAGE = factory.getOWLDataProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isApplicableToLanguage"));

    /* ***************************************************
     * Data Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isFromLanguage
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property ISFROMLANGUAGE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_ISFROMLANGUAGE = factory.getOWLDataProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#isFromLanguage"));

    /* ***************************************************
     * Data Property https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#wasInvestigatedFor
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property WASINVESTIGATEDFOR.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_WASINVESTIGATEDFOR = factory.getOWLDataProperty(IRI.create("https://metaphor.icsi.berkeley.edu/metaphor/MetaphorOntology.owl#wasInvestigatedFor"));


}
